[package]
name = "uiauto-xpath"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.62", features = [
    "Win32_UI_Accessibility",
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_System_Variant",
    "Win32_System_Ole",
] }
thiserror = "2.0.18"
regex = "1.10"
log = "0.4"
